### ISSUE TITLE
Flops and CPU inferencing

### ISSUE THREAD

**Issue by seekingdeep** [Greak-1124/LMFFNet#1]
@Greak-1124 Hi there,
1) What is the number of Flops to inference MFFLNet-S and MFFLNet-L?
2) Can it inference using cpu-only?

**Comment by Greak-1124** [comment]
1.&nbsp;When the input resolution is 512x1024, the LMFFNet-S is 14.7G and the LMFFNet-L is 16.7G.&nbsp;
2.&nbsp;Our LMFFNet can also use CPU for reasoning.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月16日(星期三) 下午3:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: [Greak-1124/LMFFNet] Flops and CPU inferencing (#1)





 
@Greak-1124 Hi there,
  
What is the number of Flops to inference MFFLNet-S and MFFLNet-L?
 
Can it inference using cpu-only?

**Comment by seekingdeep** [comment]
thanks,
Note that i would suggest pruning and quantization, to reduce the flops without loosing much miou.
good luck

**Comment by Greak-1124** [comment]
Thank you for your advice.
