### ISSUE TITLE
训练时出现的问题

### ISSUE THREAD

**Issue by Cun-bao** [Greak-1124/LMFFNet#2]
您好，我在使用单GPU（A5000）进行复现的时候，在跑完一个epoch验证后就卡在这个地方，不继续执行了。想请问您有没有遇到过这种情况
![image](https://user-images.githubusercontent.com/119907618/218944457-42024e00-75ae-435e-b024-b23b337c3a89.png)

**Comment by zxmyyds** [comment]
等待一会就出结果了
